export const BLOG_CATEGORIES = [
  "Ambiente",
  "Architettura",
  "Arte",
  "Astronomia",
  "Attualità",
  "Auto e Motori",
  "Benessere",
  "Casa e Arredamento",
  "Cinema e Serie TV",
  "Cucina",
  "Cultura",
  "Design",
  "Diritto",
  "Economia",
  "Educazione",
  "Filosofia",
  "Finanza Personale",
  "Fotografia",
  "Fumetti e Graphic Novel",
  "Gaming",
  "Geopolitica",
  "Intelligenza Artificiale",
  "Letteratura",
  "Lifestyle",
  "Moda",
  "Musica",
  "Natura e Animali",
  "Podcast e Audio",
  "Politica",
  "Psicologia",
  "Salute",
  "Scienza",
  "Società",
  "Sport",
  "Storia",
  "Startup e Imprenditoria",
  "Sostenibilità",
  "Teatro e Danza",
  "Tecnologia",
  "Viaggi"
];
